// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    register_container: string;
    form_container: string;
    register_form: string;
    register_input: string;
    btn_container: string;
    register_btn: string;
    already_par: string;
}
export const cssExports: CssExports;
export default cssExports;
